name: Flutter CI

on:
  push:
    branches:
      - master

jobs:
  version:
    name: Create version number
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
#      - name: Fetch all history for all tags and branches
#        run: |
#          git config remote.origin.url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#          git fetch --prune --depth=10000
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.9.7
        with:
          versionSpec: "5.x"
      - name: gitversion
        uses: gittools/actions/gitversion/execute@v0.9.7
      - name: Create version.txt with nuGetVersion
        run: echo ${{ steps.gitversion.outputs.GitVersion_FullSemVer  }} > version.txt
      - name: Capture version in version.txt
        run: |
          echo "GitVersion Output: ${{ steps.gitversion.outputs.GitVersion_FullSemVer }}"
      - name: Set version output
        run: echo "VERSION=${{ steps.gitversion.outputs.GitVersion_FullSemVer }}" >> $GITHUB_ENV
      - name: Use version in subsequent steps
        run: | 
          echo "Current Version1111: $VERSION"
      - name: Debug GitVersion Output
        run: |
          echo "GitVersion Output: ${{ steps.gitversion.outputs.GitVersion_FullSemVer }}"
      - name: Debug version.txt
        run: cat version.txt
      - name: Upload version.txt
        uses: actions/upload-artifact@v2
        with:
          name: gitversion
          path: version.txt
        if: success()
      - name: Handle error
        if: failure()
        run: | 
          echo "Workflow failed: ${{ job.status }}"

  build:
    name: Build APK and Create release
    needs: [ version ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Get version.txt
        uses: actions/download-artifact@v2
        with:
          name: gitversion
      - name: Display artifact contents
        run: |
          chmod +r ./version.txt
          cat ./version.txt
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: ./version.txt
          trim: true
      - name: Debug GitVersion Output
        run: |
         echo "GitVersion Output: ${{ toJson(steps.gitversion.outputs)  }}"
      - name: Debugging Info
        run: |
          echo "Content: ${{ steps.gitversion.outputs.GitVersion_FullSemVer }}"
          echo "Run Number: ${{ github.run_number }}"
          sed -i 's/99.99.99+99/${{ steps.gitversion.outputs.GitVersion_FullSemVer }}+${{ github.run_number }}/g' pubspec.yaml
          cat pubspec.yaml
      - name: Update version in YAML
        #run: sed -i 's/99.99.99+99/${{ steps.version.outputs.content }}+${{ github.run_number }}/g' pubspec.yaml
        run:
          sed -i 's/99.99.99+99/${{ steps.gitversion.outputs.GitVersion_FullSemVer }}+${{ github.run_number }}/g' pubspec.yaml

#      - uses: actions/setup-java@v1
#        with:
#          java-version: '16.x'
#
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: "3.7.0"
#          channel: 'stable'
#
#      - run: flutter pub get
#      - run: flutter build apk --release
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: release-apk
#          path: build/app/outputs/flutter-apk/app-release.apk

#      - name: Create a Release in GitHub
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/release/*.apk"
#          token: ${{ secrets.TOKEN_GITHUB }}
#          tag: ${{ steps.version.outputs.content }}
#          commit: ${{ github.sha }}



