#name: Flutter CI
#
#on:
#  push:
#    branches:
#      - master
#
#
#jobs:
##  job1:
##    runs-on: ubuntu-latest
##    # Map a step output to a job output
##    outputs:
##      output1: ${{ steps.step1.outputs.test }}
##      output2: ${{ steps.step2.outputs.test }}
##    steps:
##      - id: step1
##        run: echo "test=hello" >> "$GITHUB_OUTPUT"
##      - id: step2
##        run: echo "test=world" >> "$GITHUB_OUTPUT"
##  job2:
##    runs-on: ubuntu-latest
##    needs: job1
##    steps:
##      - env:
##          OUTPUT1: ${{needs.job1.outputs.output1}}
##          OUTPUT2: ${{needs.job1.outputs.output2}}
##        run: echo "$OUTPUT1 $OUTPUT2"
#
#  version:
#    name: Create version number
#    runs-on: ubuntu-latest
#    outputs:
#      output1: ${{ steps.step1.outputs.test }}
#    steps:
#      - uses: actions/checkout@v1
#      - name: Install GitVersion
#        uses: gittools/actions/gitversion/setup@v0.9.7
#        with:
#          versionSpec: "5.x"
#      - name: gitversion
#        uses: gittools/actions/gitversion/execute@v0.9.7
#      - name: Create version.txt with nuGetVersion
#        run: echo ${{ steps.gitversion.outputs.GitVersion_FullSemVer  }} > version.txt
#      - name: Set version output
#        id: step1
#        run: echo "test=${{ env.GitVersion_FullSemVer }}" >> $GITHUB_OUTPUT
#      - name: Upload version.txt as an artifact
#        uses: actions/upload-artifact@v2
#        with:
#          name: version-artifact
#          path: version.txt
#        if: success()
#      - name: Handle error
#        if: failure()
#        run: |
#          echo "Workflow failed: ${{ job.status }}"
#
#
#  build:
#    name: Build APK and Create release
#    needs: version
#    runs-on: ubuntu-latest
#    steps:
#      - env:
#          OUTPUT1: ${{needs.version.outputs.output1}}
#        run: echo "$OUTPUT1"
#      - uses: actions/checkout@v1
#      - name: Download version.txt artifact
#        uses: actions/download-artifact@v2
#        with:
#          name: version-artifact
#          path: downloaded
#      - name: Print version.txt content in build job
#        run: cat downloaded/version.txt
#      - name: Update version in YAML
#        run: |
#          current_version=$(grep -oP 'version: \K[0-9]+\.[0-9]+\.[0-9]+\+[0-9]+' pubspec.yaml)
#          IFS='+' read -ra version_parts <<< "$current_version"
#          new_version="${version_parts[0]}+$((${version_parts[1]}+1))"
#          sed -i "s/version: $current_version/version: ${{ needs.version.outputs.output1 }}/g" pubspec.yaml
#      - name: Print pubspec.yaml
#        run: cat pubspec.yaml
#      - uses: actions/setup-java@v1
#        with:
#          java-version: '16.x'
#
#      - uses: subosito/flutter-action@v2
#        with:
#          flutter-version: "3.7.0"
#          channel: 'stable'
#
#      - run: flutter pub get
#      - run: flutter build apk --release
#
#      - uses: actions/upload-artifact@v2
#        with:
#          name: release-apk
#          path: build/app/outputs/flutter-apk/app-release.apk
#
#      - name: Create a Release in GitHub
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/apk/release/*.apk"
#          token: ${{ secrets.TOKEN_GITHUB }}
#          tag: ${{ needs.version.outputs.output1 }}
#          commit: ${{ github.sha }}
#
#
#
#name: Auto-generate Pull Request
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  createPr:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2
#       - uses: actions/setup-java@v1
#         with:
#           java-version: '16.x'
#
#       - uses: subosito/flutter-action@v2
#         with:
#           flutter-version: "3.7.0"
#           channel: 'stable'
#       - name: Fetch latest changes
#         run: git fetch origin
#       - name: Display branch information
#         run: git branch -avv
#       - name: extract git commit data
#         uses: rlespinasse/git-commit-data-action@v1.x
#
#       - name: Print git commit data
#         run: |
#           echo "Get commit info"
#           echo " - ${{ env.GIT_COMMIT_SHA }}"
#           echo " - ${{ env.GIT_COMMIT_SHORT_SHA }}"
#           echo "Get author info"
#           echo " - ${{ env.GIT_COMMIT_AUTHOR }}"
#           echo " - ${{ env.GIT_COMMIT_AUTHOR_NAME }}"
#           echo " - ${{ env.GIT_COMMIT_AUTHOR_EMAIL }}"
#           echo "Get committer info"
#           echo " - ${{ env.GIT_COMMIT_COMMITTER }}"
#           echo " - ${{ env.GIT_COMMIT_COMMITTER_NAME }}"
#           echo " - ${{ env.GIT_COMMIT_COMMITTER_EMAIL }}"
#           echo "Get message info"
#           echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT }}"
#           echo " - ${{ env.GIT_COMMIT_MESSAGE_SUBJECT_SANITIZED }}"
#           echo " - ${{ env.GIT_COMMIT_MESSAGE_BODY }}"
#
#       - name: Create Pull Request
#         uses: peter-evans/create-pull-request@v3
#         with:
#           token: ${{ secrets.TOKEN_GITHUB }}
#           base: master
#           branch: testing_pr
#           title: Automatic PR from master to nam
#           body:  Changes from the master branch have been automatically pushed to the nam branch.

